---
  concat:
    options:
      banner: ";(function(moduleFunc) {if (typeof define === 'function' && define.amd) {define('jquery.fn.miniBarrages', ['jquery','lodash','moment'], moduleFunc);}else {moduleFunc(jQuery, _, moment);}})(function($, _, moment) {\n"
      footer: "\n});"
    src:
      - src/js-mini-barrages/class/**/*.js
      - src/js-mini-barrages/component/**/*.js
      - src/js-mini-barrages/element/**/*.js
      - src/js-mini-barrages/util/**/*.js
      - src/js-mini-barrages/app.js
    dest: dest/js/es2015-mini-barrages.js

  babel:
    options:
      presets:
        - babel-preset-es2015
    files:
      dest/js/mini-barrages.js: "<%= concat['js-mini-barrages'].dest %>"

  uglify:
    src: dest/js/mini-barrages.js
    dest: dest/js/mini-barrages.min.js

  watch:
    files:
      - src/js-mini-barrages/**/*.js
    tasks:
      - task/js/mini/barrages